# Generated by Django 3.1.2 on 2020-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('type_plane', models.IntegerField(choices=[(1, 'Business'), (2, 'Medium'), (3, 'Econome')])),
            ],
        ),
    ]
