# Generated by Django 3.1.2 on 2020-11-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20201027_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
