# Generated by Django 3.1.2 on 2020-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='type_plane',
            field=models.IntegerField(choices=[(1, 'Business'), (2, 'Medium'), (3, 'Econome')]),
        ),
    ]
