# Generated by Django 3.1.2 on 2020-10-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20201026_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='type_plane',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
