# Generated by Django 3.1.2 on 2020-10-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_auto_20201026_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plane',
        ),
    ]
